#include "amici/symbolic_functions.h"
#include "amici/defines.h"
#include "sundials/sundials_types.h"

#include <gsl/gsl-lite.hpp>
#include <array>
#include <algorithm>

#include "SPARCED_x.h"
#include "SPARCED_tcl.h"
#include "SPARCED_p.h"
#include "SPARCED_dx_rdatadtcl.h"

namespace amici {
namespace model_SPARCED {

void dx_rdatadtcl_SPARCED(realtype *dx_rdatadtcl, const realtype *x, const realtype *tcl, const realtype *p, const realtype *k){
    dm_INS_dtcl_m_INS = 1;  // dx_rdatadtcl[0]
    dm_INSR_dtcl_m_INSR = 1;  // dx_rdatadtcl[1]
    dm_MGMT_dtcl_m_MGMT = 1;  // dx_rdatadtcl[2]
    dm_BRCA2_dtcl_m_BRCA2 = 1;  // dx_rdatadtcl[3]
    dm_MSH6_dtcl_m_MSH6 = 1;  // dx_rdatadtcl[4]
    dm_IGF1R_dtcl_m_IGF1R = 1;  // dx_rdatadtcl[5]
    dm_IGF2_dtcl_m_IGF2 = 1;  // dx_rdatadtcl[6]
    dm_IGF1_dtcl_m_IGF1 = 1;  // dx_rdatadtcl[7]
    dm_IRS2_dtcl_m_IRS2 = 1;  // dx_rdatadtcl[8]
    dm_IRS1_dtcl_m_IRS1 = 1;  // dx_rdatadtcl[9]
    dm_EIF4E_dtcl_m_EIF4E = 1;  // dx_rdatadtcl[10]
    dm_FGF2_dtcl_m_FGF2 = 1;  // dx_rdatadtcl[11]
    dm_FGF1_dtcl_m_FGF1 = 1;  // dx_rdatadtcl[12]
    dm_FGFR2_dtcl_m_FGFR2 = 1;  // dx_rdatadtcl[13]
    dm_FGFR1_dtcl_m_FGFR1 = 1;  // dx_rdatadtcl[14]
    dm_MDM4_dtcl_m_MDM4 = 1;  // dx_rdatadtcl[15]
    dm_CDKN2A_dtcl_m_CDKN2A = 1;  // dx_rdatadtcl[16]
    dm_SOS1_dtcl_m_SOS1 = 1;  // dx_rdatadtcl[17]
    dm_EIF4EBP1_dtcl_m_EIF4EBP1 = 1;  // dx_rdatadtcl[18]
    dm_RPS6KB2_dtcl_m_RPS6KB2 = 1;  // dx_rdatadtcl[19]
    dm_RPS6KB1_dtcl_m_RPS6KB1 = 1;  // dx_rdatadtcl[20]
    dm_RPTOR_dtcl_m_RPTOR = 1;  // dx_rdatadtcl[21]
    dm_RHEB_dtcl_m_RHEB = 1;  // dx_rdatadtcl[22]
    dm_FOXO3_dtcl_m_FOXO3 = 1;  // dx_rdatadtcl[23]
    dm_MAPK3_dtcl_m_MAPK3 = 1;  // dx_rdatadtcl[24]
    dm_MAPK1_dtcl_m_MAPK1 = 1;  // dx_rdatadtcl[25]
    dm_PEBP1_dtcl_m_PEBP1 = 1;  // dx_rdatadtcl[26]
    dm_PRKCD_dtcl_m_PRKCD = 1;  // dx_rdatadtcl[27]
    dm_PRKCG_dtcl_m_PRKCG = 1;  // dx_rdatadtcl[28]
    dm_PRKCB_dtcl_m_PRKCB = 1;  // dx_rdatadtcl[29]
    dm_PRKCA_dtcl_m_PRKCA = 1;  // dx_rdatadtcl[30]
    dm_TSC2_dtcl_m_TSC2 = 1;  // dx_rdatadtcl[31]
    dm_TSC1_dtcl_m_TSC1 = 1;  // dx_rdatadtcl[32]
    dm_GSK3B_dtcl_m_GSK3B = 1;  // dx_rdatadtcl[33]
    dm_MTOR_dtcl_m_MTOR = 1;  // dx_rdatadtcl[34]
    dm_RICTOR_dtcl_m_RICTOR = 1;  // dx_rdatadtcl[35]
    dm_PDPK1_dtcl_m_PDPK1 = 1;  // dx_rdatadtcl[36]
    dm_AKT2_dtcl_m_AKT2 = 1;  // dx_rdatadtcl[37]
    dm_AKT1_dtcl_m_AKT1 = 1;  // dx_rdatadtcl[38]
    dm_PTEN_dtcl_m_PTEN = 1;  // dx_rdatadtcl[39]
    dm_CTNNB1_dtcl_m_CTNNB1 = 1;  // dx_rdatadtcl[40]
    dm_MYC_dtcl_m_MYC = 1;  // dx_rdatadtcl[41]
    dm_JUN_dtcl_m_JUN = 1;  // dx_rdatadtcl[42]
    dm_FOS_dtcl_m_FOS = 1;  // dx_rdatadtcl[43]
    dm_DUSP1_dtcl_m_DUSP1 = 1;  // dx_rdatadtcl[44]
    dm_RPS6KA4_dtcl_m_RPS6KA4 = 1;  // dx_rdatadtcl[45]
    dm_RPS6KA3_dtcl_m_RPS6KA3 = 1;  // dx_rdatadtcl[46]
    dm_RPS6KA2_dtcl_m_RPS6KA2 = 1;  // dx_rdatadtcl[47]
    dm_RPS6KA1_dtcl_m_RPS6KA1 = 1;  // dx_rdatadtcl[48]
    dm_DUSP6_dtcl_m_DUSP6 = 1;  // dx_rdatadtcl[49]
    dm_MAP2K2_dtcl_m_MAP2K2 = 1;  // dx_rdatadtcl[50]
    dm_MAP2K1_dtcl_m_MAP2K1 = 1;  // dx_rdatadtcl[51]
    dm_BRAF_dtcl_m_BRAF = 1;  // dx_rdatadtcl[52]
    dm_RAF1_dtcl_m_RAF1 = 1;  // dx_rdatadtcl[53]
    dm_NF1_dtcl_m_NF1 = 1;  // dx_rdatadtcl[54]
    dm_HRAS_dtcl_m_HRAS = 1;  // dx_rdatadtcl[55]
    dm_KRAS_dtcl_m_KRAS = 1;  // dx_rdatadtcl[56]
    dm_NRAS_dtcl_m_NRAS = 1;  // dx_rdatadtcl[57]
    dm_RASGRP3_dtcl_m_RASGRP3 = 1;  // dx_rdatadtcl[58]
    dm_RASGRP1_dtcl_m_RASGRP1 = 1;  // dx_rdatadtcl[59]
    dm_PIK3C2A_dtcl_m_PIK3C2A = 1;  // dx_rdatadtcl[60]
    dm_PIK3R4_dtcl_m_PIK3R4 = 1;  // dx_rdatadtcl[61]
    dm_PIK3R3_dtcl_m_PIK3R3 = 1;  // dx_rdatadtcl[62]
    dm_PIK3R2_dtcl_m_PIK3R2 = 1;  // dx_rdatadtcl[63]
    dm_PIK3R1_dtcl_m_PIK3R1 = 1;  // dx_rdatadtcl[64]
    dm_PIK3CD_dtcl_m_PIK3CD = 1;  // dx_rdatadtcl[65]
    dm_PIK3CG_dtcl_m_PIK3CG = 1;  // dx_rdatadtcl[66]
    dm_PIK3CB_dtcl_m_PIK3CB = 1;  // dx_rdatadtcl[67]
    dm_PIK3CA_dtcl_m_PIK3CA = 1;  // dx_rdatadtcl[68]
    dm_PLCG2_dtcl_m_PLCG2 = 1;  // dx_rdatadtcl[69]
    dm_PLCG1_dtcl_m_PLCG1 = 1;  // dx_rdatadtcl[70]
    dm_GRB2_dtcl_m_GRB2 = 1;  // dx_rdatadtcl[71]
    dm_CBL_dtcl_m_CBL = 1;  // dx_rdatadtcl[72]
    dm_SPRY2_dtcl_m_SPRY2 = 1;  // dx_rdatadtcl[73]
    dm_PDGFB_dtcl_m_PDGFB = 1;  // dx_rdatadtcl[74]
    dm_PDGFRB_dtcl_m_PDGFRB = 1;  // dx_rdatadtcl[75]
    dm_PDGFRA_dtcl_m_PDGFRA = 1;  // dx_rdatadtcl[76]
    dm_HGF_dtcl_m_HGF = 1;  // dx_rdatadtcl[77]
    dm_MET_dtcl_m_MET = 1;  // dx_rdatadtcl[78]
    dm_EGFRvIII_dtcl_m_EGFRvIII = 1;  // dx_rdatadtcl[79]
    dm_ERBB4_dtcl_m_ERBB4 = 1;  // dx_rdatadtcl[80]
    dm_ERBB3_dtcl_m_ERBB3 = 1;  // dx_rdatadtcl[81]
    dm_ERBB2_dtcl_m_ERBB2 = 1;  // dx_rdatadtcl[82]
    dm_EGFR_dtcl_m_EGFR = 1;  // dx_rdatadtcl[83]
    dm_NRG1_dtcl_m_NRG1 = 1;  // dx_rdatadtcl[84]
    dm_EGF_dtcl_m_EGF = 1;  // dx_rdatadtcl[85]
    dm_BCL2L11_dtcl_m_BCL2L11 = 1;  // dx_rdatadtcl[86]
    dm_PMAIP1_dtcl_m_PMAIP1 = 1;  // dx_rdatadtcl[87]
    dm_BBC3_dtcl_m_BBC3 = 1;  // dx_rdatadtcl[88]
    dm_BAD_dtcl_m_BAD = 1;  // dx_rdatadtcl[89]
    dm_CASP9_dtcl_m_CASP9 = 1;  // dx_rdatadtcl[90]
    dm_APAF1_dtcl_m_APAF1 = 1;  // dx_rdatadtcl[91]
    dm_DIABLO_dtcl_m_DIABLO = 1;  // dx_rdatadtcl[92]
    dm_CYCS_dtcl_m_CYCS = 1;  // dx_rdatadtcl[93]
    dm_BAX_dtcl_m_BAX = 1;  // dx_rdatadtcl[94]
    dm_MCL1_dtcl_m_MCL1 = 1;  // dx_rdatadtcl[95]
    dm_BCL2L1_dtcl_m_BCL2L1 = 1;  // dx_rdatadtcl[96]
    dm_BCL2_dtcl_m_BCL2 = 1;  // dx_rdatadtcl[97]
    dm_BID_dtcl_m_BID = 1;  // dx_rdatadtcl[98]
    dm_PARP1_dtcl_m_PARP1 = 1;  // dx_rdatadtcl[99]
    dm_XIAP_dtcl_m_XIAP = 1;  // dx_rdatadtcl[100]
    dm_CASP6_dtcl_m_CASP6 = 1;  // dx_rdatadtcl[101]
    dm_CASP7_dtcl_m_CASP7 = 1;  // dx_rdatadtcl[102]
    dm_CASP3_dtcl_m_CASP3 = 1;  // dx_rdatadtcl[103]
    dm_BFAR_dtcl_m_BFAR = 1;  // dx_rdatadtcl[104]
    dm_CASP10_dtcl_m_CASP10 = 1;  // dx_rdatadtcl[105]
    dm_CASP8_dtcl_m_CASP8 = 1;  // dx_rdatadtcl[106]
    dm_CFLAR_dtcl_m_CFLAR = 1;  // dx_rdatadtcl[107]
    dm_TNFRSF10B_dtcl_m_TNFRSF10B = 1;  // dx_rdatadtcl[108]
    dm_TNFRSF10A_dtcl_m_TNFRSF10A = 1;  // dx_rdatadtcl[109]
    dm_TNFSF10_dtcl_m_TNFSF10 = 1;  // dx_rdatadtcl[110]
    dm_CDK6_dtcl_m_CDK6 = 1;  // dx_rdatadtcl[111]
    dm_CDK4_dtcl_m_CDK4 = 1;  // dx_rdatadtcl[112]
    dm_CDK2_dtcl_m_CDK2 = 1;  // dx_rdatadtcl[113]
    dm_CDK1_dtcl_m_CDK1 = 1;  // dx_rdatadtcl[114]
    dm_CDKN1A_dtcl_m_CDKN1A = 1;  // dx_rdatadtcl[115]
    dm_CHEK1_dtcl_m_CHEK1 = 1;  // dx_rdatadtcl[116]
    dm_WEE1_dtcl_m_WEE1 = 1;  // dx_rdatadtcl[117]
    dm_CDC20_dtcl_m_CDC20 = 1;  // dx_rdatadtcl[118]
    dm_CCNB1_dtcl_m_CCNB1 = 1;  // dx_rdatadtcl[119]
    dm_CDH1_dtcl_m_CDH1 = 1;  // dx_rdatadtcl[120]
    dm_CDKN1B_dtcl_m_CDKN1B = 1;  // dx_rdatadtcl[121]
    dm_CCNA2_dtcl_m_CCNA2 = 1;  // dx_rdatadtcl[122]
    dm_CDC25C_dtcl_m_CDC25C = 1;  // dx_rdatadtcl[123]
    dm_CDC25B_dtcl_m_CDC25B = 1;  // dx_rdatadtcl[124]
    dm_CDC25A_dtcl_m_CDC25A = 1;  // dx_rdatadtcl[125]
    dm_SKP2_dtcl_m_SKP2 = 1;  // dx_rdatadtcl[126]
    dm_CCNE2_dtcl_m_CCNE2 = 1;  // dx_rdatadtcl[127]
    dm_CCNE1_dtcl_m_CCNE1 = 1;  // dx_rdatadtcl[128]
    dm_CCND3_dtcl_m_CCND3 = 1;  // dx_rdatadtcl[129]
    dm_CCND2_dtcl_m_CCND2 = 1;  // dx_rdatadtcl[130]
    dm_CCND1_dtcl_m_CCND1 = 1;  // dx_rdatadtcl[131]
    dm_E2F3_dtcl_m_E2F3 = 1;  // dx_rdatadtcl[132]
    dm_E2F2_dtcl_m_E2F2 = 1;  // dx_rdatadtcl[133]
    dm_E2F1_dtcl_m_E2F1 = 1;  // dx_rdatadtcl[134]
    dm_RB1_dtcl_m_RB1 = 1;  // dx_rdatadtcl[135]
    dm_ATR_dtcl_m_ATR = 1;  // dx_rdatadtcl[136]
    dm_ATM_dtcl_m_ATM = 1;  // dx_rdatadtcl[137]
    dm_PPM1D_dtcl_m_PPM1D = 1;  // dx_rdatadtcl[138]
    dm_MDM2_dtcl_m_MDM2 = 1;  // dx_rdatadtcl[139]
    dm_TP53_dtcl_m_TP53 = 1;  // dx_rdatadtcl[140]
}

} // namespace model_SPARCED
} // namespace amici
